import type { Metadata } from "next";
import "./globals.css";
import MuiWrapper from "@/components/Wrappers/MuiWrapper";

export const metadata: Metadata = {
  title: "Create Next App 2",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MuiWrapper>{children}</MuiWrapper>
      </body>
    </html>
  );
}
